### ISSUE TITLE
Broken data download links

### ISSUE THREAD

**Issue by bbonf** [UiL-OTS-labs/web-experiment-datastore#34]
`Download raw data` and  `Download data as CSV` links on My Experiments page are broken.

For some reason the experiment id is undefined in the url, e.g.:

https://experiment-datastore.lab.hum.uu.nl/experiments/undefined/data/raw/

**Comment by tymees** [comment]
Do you have an experiment to test on?

My test experiments all work

**Comment by tymees** [comment]
Hmmm wait nevermind, I was looking at the wrong page

**Comment by tymees** [comment]
Should be fixed in the linked PR. If you want to test it locally, go ahead. Otherwise I'll just merge

**Comment by bbonf** [comment]
Works for me
