### ISSUE TITLE
Piloting state for experiments

### ISSUE THREAD

**Issue by bbonf** [UiL-OTS-labs/web-experiment-datastore#41]
We currently have a 'Piloting' state for experiments, but it doesn't do anything.
When your experiment is set to piloting:
- You cannot start a new participant session
- You cannot upload data

Which means it's basically the same as leaving the experiment closed.

A better use of the piloting state would be if we let you start sessions and upload data, but later mark those sessions and data as pilot data.
The basis for it already exists in `ParticipantSession.experiment_state`, but that's not currently used, and it is blocked by `Experiment.is_open` anyway.

**Comment by tymees** [comment]
It does actually do something, but not in this app. It's used by the utils library to allow access (if it's closed, the library redirects to a generic closed page). The reason why we didn't allow data upload was to avoid confusion on the researchers path. However, I could live with marking it as pilot data (but it would also add more complexity to the group assignment logic, which is less ideal)

**Comment by bbonf** [comment]
Ok, thanks for bringing this up.

One thing I forgot to mention - not being able to create sessions when your experiment is set to piloting, also means that you cannot run an experiment locally: the server refuses to open a session and then the experiment can't start.

**Comment by tymees** [comment]
Well that is a problem then yes, so maybe the extra complexity is needed anyway then
