### ISSUE TITLE
Upload fails when using sessions with only a single group

### ISSUE THREAD

**Issue by bbonf** [UiL-OTS-labs/web-experiment-datastore#50]
Because of the way `Experiment.uses_groups()` works, it is currently possible to start an experiment when only a single group is configured, but it's impossible to save the participant's data.

This is caused by the following exception in SessionUploadView:
```
        if not self.experiment.uses_groups():
            raise ValidationError(detail='Experiment is not using session ids')
```

**Comment by tymees** [comment]
I'd say that SessionUploadView is right, but ParticipantView isn't?

If there is one group defined, one should use the regular api endpoint for uploads
