### ISSUE TITLE
Weird order of groups when adding multiple groups.

### ISSUE THREAD

**Issue by maartenuni** [UiL-OTS-labs/web-experiment-datastore#64]
When adding multiple groups to an experiment, the first group stays in place (maybe because it is saved), the second group is added when, so far so good. However, when a third group is added, the second group is moved to the third place and an empty group is inserted between the saved groups and the previously added groups.
This is weird to the users, because they would expect the group to be added at the bottom and not in the middle.
The strange behavior occurs after clicking the "+ Add target group" link, but prior to clicking save

**Comment by tymees** [comment]
Does this happen after save actions? In which case, it might just be that TargetGroup doesn't have a default order_by.

**Comment by maartenuni** [comment]
No, this happens prior to saving, probably, the javascript on the page needs a little update.
