### ISSUE TITLE
Upgrade to DSC 3.0

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/web-experiment-datastore#67]
The future is here! We'll need to upgrade to this future at some point. 

In general, the migration guide can be used: https://dh-it-portal-development.github.io/django-shared-core/

However, for this app there are some extra things to do/consider:
- Adding Django Impersonate (#60)
- It's _recommended_ to upgrade to Django 4.0 as well
- Introducing an 'app' color; this is something Ben and I talked about, to better differentiate our apps. The idea that every app should use one color as it's main highlight. 

I can't assign to multiple people, so I'm just gonna namedrop: @maartenuni @bbonf

**Comment by bbonf** [comment]
Fixed in #68 right?

**Comment by tymees** [comment]
Jup
